const ShopActionTypes = {
    FETCH_ALL_COLLECTIONS_START: 'FETCH_ALL_COLLECTIONS_START',
    FETCH_MENS_COLLECTION_START: 'FETCH_MENS_COLLECTION_START',
    FETCH_WOMENS_COLLECTION_START: 'FETCH_WOMENS_COLLECTION_START',
    FETCH_AJ1_COLLECTION_START: 'FETCH_AJ1_COLLECTION_START',
    FETCH_BBALL_COLLECTION_START: 'FETCH_BBALL_COLLECTION_START',
    FETCH_SNKRS_COLLECTION_START: 'FETCH_SNKRS_COLLECTION_START',
    FETCH_CUSTOM_PARAMS_START: 'FETCH_CUSTOM_PARAMS_START',
    FETCH_COLLECTIONS_SUCCESS: 'FETCH_COLLECTIONS_SUCCESS',
    FETCH_COLLECTIONS_FAILURE: 'FETCH_COLLECTIONS_FAILURE'
};

export default ShopActionTypes;
