const ShopActionTypes = {
    TOGGLE_FILTER_BAR_HIDDEN: 'TOGGLE_FILTER_BAR_HIDDEN',
    FETCH_ALL_SHOES_START: 'FETCH_ALL_SHOES_START',
    FETCH_SHOES_SUCCESS: 'FETCH_SHOES_SUCCESS',
    FETCH_SHOES_FAILURE: 'FETCH_SHOES_FAILURE'
};

export default ShopActionTypes;
