const ShopActionTypes = {
    FETCH_ALL_SHOES_START: 'FETCH_ALL_SHOES_START',
    FETCH_SHOE_BY_ID_START: 'FETCH_SHOE_BY_ID_START',
    FETCH_SHOES_SUCCESS: 'FETCH_SHOES_SUCCESS',
    FETCH_SHOES_FAILURE: 'FETCH_SHOES_FAILURE',
    FETCH_SHOE_BY_ID_SUCCESS: 'FETCH_SHOE_BY_ID_SUCCESS',
    FETCH_SHOE_BY_ID_FAILURE: 'FETCH_SHOE_BY_ID_FAILURE'
};

export default ShopActionTypes;
