const FavouriteActionTypes = {
  ADD_ITEM_TO_FAVOURITE: "ADD_ITEM_TO_FAVOURITE",
  CLEAR_ITEM_FROM_FAVOURITE: "CLEAR_ITEM_FROM_FAVOURITE",
  TOGGLE_FAVOURITE_MODAL: "TOGGLE_FAVOURITE_MODAL",
};

export default FavouriteActionTypes;
